(global-set-key (kbd "<f8> - >") (lambda () (interactive) (insert "→") ))
(global-set-key (kbd "<f8> < - SPC") (lambda () (interactive) (insert "←") ))
(global-set-key (kbd "<f8> < - >") (lambda () (interactive) (insert "↔") ))
(global-set-key (kbd "<f8> | - >") (lambda () (interactive) (insert "↦") ))
(global-set-key (kbd "<f8> = >") (lambda () (interactive) (insert "⇒") ))
(global-set-key (kbd "<f8> < = SPC") (lambda () (interactive) (insert "⇐") ))
(global-set-key (kbd "<f8> < = >") (lambda () (interactive) (insert "⇔") ))
(global-set-key (kbd "<f8> ~ >") (lambda () (interactive) (insert "↬") ))
(global-set-key (kbd "<f8> / 0") (lambda () (interactive) (insert "∅") ))
(global-set-key (kbd "<f8> e") (lambda () (interactive) (insert "ϵ") ))
(global-set-key (kbd "<f8> (") (lambda () (interactive) (insert "⊂") ))
(global-set-key (kbd "<f8> _ (") (lambda () (interactive) (insert "⊆") ))
(global-set-key (kbd "<f8> )") (lambda () (interactive) (insert "⊃") ))
(global-set-key (kbd "<f8> _ )") (lambda () (interactive) (insert "⊇") ))
(global-set-key (kbd "<f8> ! (") (lambda () (interactive) (insert "⊄") ))
(global-set-key (kbd "<f8> ! _ (") (lambda () (interactive) (insert "⊈") ))
(global-set-key (kbd "<f8> ! )") (lambda () (interactive) (insert "⊅") ))
(global-set-key (kbd "<f8> ! _ )") (lambda () (interactive) (insert "⊉") ))
(global-set-key (kbd "<f8> U") (lambda () (interactive) (insert "⋃") ))
(global-set-key (kbd "<f8> n") (lambda () (interactive) (insert "⋂") ))
(global-set-key (kbd "<f8> C SPC") (lambda () (interactive) (insert "∁") ))
(global-set-key (kbd "<f8> ! SPC") (lambda () (interactive) (insert "¬") ))
(global-set-key (kbd "<f8> v SPC") (lambda () (interactive) (insert "∨") ))
(global-set-key (kbd "<f8> ^ SPC") (lambda () (interactive) (insert "∧") ))
(global-set-key (kbd "<f8> - v") (lambda () (interactive) (insert "⊽") ))
(global-set-key (kbd "<f8> - ^ SPC") (lambda () (interactive) (insert "⊼") ))
(global-set-key (kbd "<f8> _ v") (lambda () (interactive) (insert "⊻") ))
(global-set-key (kbd "<f8> < >") (lambda () (interactive) (insert "◇") ))
(global-set-key (kbd "<f8> [ ]") (lambda () (interactive) (insert "◻") ))
(global-set-key (kbd "<f8> A") (lambda () (interactive) (insert "∀") ))
(global-set-key (kbd "<f8> E") (lambda () (interactive) (insert "∃") ))
(global-set-key (kbd "<f8> ! E") (lambda () (interactive) (insert "∄") ))
(global-set-key (kbd "<f8> | =") (lambda () (interactive) (insert "⊨") ))
(global-set-key (kbd "<f8> ! | =") (lambda () (interactive) (insert "⊭") ))
(global-set-key (kbd "<f8> | - SPC") (lambda () (interactive) (insert "⊢") ))
(global-set-key (kbd "<f8> ! | -") (lambda () (interactive) (insert "⊬") ))
(global-set-key (kbd "<f8> ^ SPC") (lambda () (interactive) (insert "∧") ))
(global-set-key (kbd "<f8> ^ SPC") (lambda () (interactive) (insert "∧") ))
(global-set-key (kbd "<f8> _ |") (lambda () (interactive) (insert "⊥") ))
(global-set-key (kbd "<f8> T ") (lambda () (interactive) (insert "⊤") ))
(global-set-key (kbd "<f8> . :") (lambda () (interactive) (insert "∴") ))
(global-set-key (kbd "<f8> : .") (lambda () (interactive) (insert "∵") ))
(global-set-key (kbd "<f8> 8") (lambda () (interactive) (insert "∞") ))
(global-set-key (kbd "<f8> S SPC") (lambda () (interactive) (insert "∫") ))
(global-set-key (kbd "<f8> o S") (lambda () (interactive) (insert "∮") ))
(global-set-key (kbd "<f8> ! | SPC") (lambda () (interactive) (insert "∤") ))
(global-set-key (kbd "<f8> | |") (lambda () (interactive) (insert "∥") ))
(global-set-key (kbd "<f8> ! | |") (lambda () (interactive) (insert "∦") ))
(global-set-key (kbd "<f8> _ [") (lambda () (interactive) (insert "⌊") ))
(global-set-key (kbd "<f8> _ ]") (lambda () (interactive) (insert "⌋") ))
(global-set-key (kbd "<f8> ^ [") (lambda () (interactive) (insert "⌈") ))
(global-set-key (kbd "<f8> ^ ]") (lambda () (interactive) (insert "⌉") ))
(global-set-key (kbd "<f8> [ |") (lambda () (interactive) (insert "⟦") ))
(global-set-key (kbd "<f8> | ]") (lambda () (interactive) (insert "⟧") ))
(global-set-key (kbd "<f8> < [") (lambda () (interactive) (insert "⟨") ))
(global-set-key (kbd "<f8> ] >") (lambda () (interactive) (insert "⟩") ))
(global-set-key (kbd "<f8> _ =") (lambda () (interactive) (insert "≡") ))
(global-set-key (kbd "<f8> _ >") (lambda () (interactive) (insert "≥") ))
(global-set-key (kbd "<f8> _ <") (lambda () (interactive) (insert "≤") ))
(global-set-key (kbd "<f8> ! =") (lambda () (interactive) (insert "≠") ))
(global-set-key (kbd "<f8> ~ ~") (lambda () (interactive) (insert "≈") ))
(global-set-key (kbd "<f8> ~ =") (lambda () (interactive) (insert "≅") ))
(global-set-key (kbd "<f8> . SPC") (lambda () (interactive) (insert "·") ))
(global-set-key (kbd "<f8> x SPC") (lambda () (interactive) (insert "×") ))
(global-set-key (kbd "<f8> / SPC") (lambda () (interactive) (insert "÷") ))
(global-set-key (kbd "<f8> + -") (lambda () (interactive) (insert "±") ))
(global-set-key (kbd "<f8> o SPC") (lambda () (interactive) (insert "∘") ))
(global-set-key (kbd "<f8> o +") (lambda () (interactive) (insert "⊕") ))
(global-set-key (kbd "<f8> o -") (lambda () (interactive) (insert "⊖") ))
(global-set-key (kbd "<f8> o x") (lambda () (interactive) (insert "⊗") ))
(global-set-key (kbd "<f8> o /") (lambda () (interactive) (insert "⊘") ))
(global-set-key (kbd "<f8> o .") (lambda () (interactive) (insert "⊙") ))
(global-set-key (kbd "<f8> o o") (lambda () (interactive) (insert "⊚") ))
(global-set-key (kbd "<f8> o *") (lambda () (interactive) (insert "⊛") ))
(global-set-key (kbd "<f8> o =") (lambda () (interactive) (insert "⊜") ))
(global-set-key (kbd "<f8> [ + ]") (lambda () (interactive) (insert "⊞") ))
(global-set-key (kbd "<f8> [ - ]") (lambda () (interactive) (insert "⊟") ))
(global-set-key (kbd "<f8> [ x ]") (lambda () (interactive) (insert "⊠") ))
(global-set-key (kbd "<f8> [ . ]") (lambda () (interactive) (insert "⊡") ))
(global-set-key (kbd "<f8> 1 4") (lambda () (interactive) (insert "¼") ))
(global-set-key (kbd "<f8> 1 2") (lambda () (interactive) (insert "½") ))
(global-set-key (kbd "<f8> 3 4") (lambda () (interactive) (insert "¾") ))
(global-set-key (kbd "<f8> _ 0") (lambda () (interactive) (insert "₀") ))
(global-set-key (kbd "<f8> _ 1") (lambda () (interactive) (insert "₁") ))
(global-set-key (kbd "<f8> _ 2") (lambda () (interactive) (insert "₂") ))
(global-set-key (kbd "<f8> _ 3") (lambda () (interactive) (insert "₃") ))
(global-set-key (kbd "<f8> _ 4") (lambda () (interactive) (insert "₄") ))
(global-set-key (kbd "<f8> _ 5") (lambda () (interactive) (insert "₅") ))
(global-set-key (kbd "<f8> _ 6") (lambda () (interactive) (insert "₆") ))
(global-set-key (kbd "<f8> _ 7") (lambda () (interactive) (insert "₇") ))
(global-set-key (kbd "<f8> _ 8") (lambda () (interactive) (insert "₈") ))
(global-set-key (kbd "<f8> _ 9") (lambda () (interactive) (insert "₉") ))
(global-set-key (kbd "<f8> _ +") (lambda () (interactive) (insert "₊") ))
(global-set-key (kbd "<f8> _ -") (lambda () (interactive) (insert "₋") ))
(global-set-key (kbd "<f8> ^ 0") (lambda () (interactive) (insert "⁰") ))
(global-set-key (kbd "<f8> ^ 1") (lambda () (interactive) (insert "¹") ))
(global-set-key (kbd "<f8> ^ 2") (lambda () (interactive) (insert "²") ))
(global-set-key (kbd "<f8> ^ 3") (lambda () (interactive) (insert "³") ))
(global-set-key (kbd "<f8> ^ 4") (lambda () (interactive) (insert "⁴") ))
(global-set-key (kbd "<f8> ^ 5") (lambda () (interactive) (insert "⁵") ))
(global-set-key (kbd "<f8> ^ 6") (lambda () (interactive) (insert "⁶") ))
(global-set-key (kbd "<f8> ^ 7") (lambda () (interactive) (insert "⁷") ))
(global-set-key (kbd "<f8> ^ 8") (lambda () (interactive) (insert "⁸") ))
(global-set-key (kbd "<f8> ^ 9") (lambda () (interactive) (insert "⁹") ))
(global-set-key (kbd "<f8> ^ +") (lambda () (interactive) (insert "⁺") ))
(global-set-key (kbd "<f8> ^ -") (lambda () (interactive) (insert "⁻") ))
(global-set-key (kbd "<f8> g A") (lambda () (interactive) (insert "Α") ))
(global-set-key (kbd "<f8> g a") (lambda () (interactive) (insert "α") ))
(global-set-key (kbd "<f8> g B") (lambda () (interactive) (insert "Β") ))
(global-set-key (kbd "<f8> g b") (lambda () (interactive) (insert "β") ))
(global-set-key (kbd "<f8> g C") (lambda () (interactive) (insert "Ψ") ))
(global-set-key (kbd "<f8> g c") (lambda () (interactive) (insert "ψ") ))
(global-set-key (kbd "<f8> g D") (lambda () (interactive) (insert "Δ") ))
(global-set-key (kbd "<f8> g d") (lambda () (interactive) (insert "δ") ))
(global-set-key (kbd "<f8> g E") (lambda () (interactive) (insert "Ε") ))
(global-set-key (kbd "<f8> g e") (lambda () (interactive) (insert "ε") ))
(global-set-key (kbd "<f8> g F") (lambda () (interactive) (insert "Φ") ))
(global-set-key (kbd "<f8> g f") (lambda () (interactive) (insert "φ") ))
(global-set-key (kbd "<f8> g G") (lambda () (interactive) (insert "Γ") ))
(global-set-key (kbd "<f8> g g") (lambda () (interactive) (insert "γ") ))
(global-set-key (kbd "<f8> g H") (lambda () (interactive) (insert "Η") ))
(global-set-key (kbd "<f8> g h") (lambda () (interactive) (insert "η") ))
(global-set-key (kbd "<f8> g I") (lambda () (interactive) (insert "Ι") ))
(global-set-key (kbd "<f8> g i") (lambda () (interactive) (insert "ι") ))
(global-set-key (kbd "<f8> g J") (lambda () (interactive) (insert "Ξ") ))
(global-set-key (kbd "<f8> g j") (lambda () (interactive) (insert "ξ") ))
(global-set-key (kbd "<f8> g K") (lambda () (interactive) (insert "Κ") ))
(global-set-key (kbd "<f8> g k") (lambda () (interactive) (insert "κ") ))
(global-set-key (kbd "<f8> g L") (lambda () (interactive) (insert "Λ") ))
(global-set-key (kbd "<f8> g l") (lambda () (interactive) (insert "λ") ))
(global-set-key (kbd "<f8> g M") (lambda () (interactive) (insert "Μ") ))
(global-set-key (kbd "<f8> g m") (lambda () (interactive) (insert "μ") ))
(global-set-key (kbd "<f8> g N") (lambda () (interactive) (insert "Ν") ))
(global-set-key (kbd "<f8> g n") (lambda () (interactive) (insert "ν") ))
(global-set-key (kbd "<f8> g O") (lambda () (interactive) (insert "Ο") ))
(global-set-key (kbd "<f8> g o") (lambda () (interactive) (insert "ο") ))
(global-set-key (kbd "<f8> g P") (lambda () (interactive) (insert "Π") ))
(global-set-key (kbd "<f8> g p") (lambda () (interactive) (insert "π") ))
(global-set-key (kbd "<f8> g Q") (lambda () (interactive) (insert "ϰ") ))
(global-set-key (kbd "<f8> g q") (lambda () (interactive) (insert "ϡ") ))
(global-set-key (kbd "<f8> g R") (lambda () (interactive) (insert "Ρ") ))
(global-set-key (kbd "<f8> g r") (lambda () (interactive) (insert "ρ") ))
(global-set-key (kbd "<f8> g S") (lambda () (interactive) (insert "Σ") ))
(global-set-key (kbd "<f8> g s") (lambda () (interactive) (insert "σ") ))
(global-set-key (kbd "<f8> g T") (lambda () (interactive) (insert "Τ") ))
(global-set-key (kbd "<f8> g t") (lambda () (interactive) (insert "τ") ))
(global-set-key (kbd "<f8> g U") (lambda () (interactive) (insert "Θ") ))
(global-set-key (kbd "<f8> g u") (lambda () (interactive) (insert "θ") ))
(global-set-key (kbd "<f8> g V") (lambda () (interactive) (insert "Ω") ))
(global-set-key (kbd "<f8> g v") (lambda () (interactive) (insert "ω") ))
(global-set-key (kbd "<f8> g W") (lambda () (interactive) (insert "ϖ") ))
(global-set-key (kbd "<f8> g w") (lambda () (interactive) (insert "ς") ))
(global-set-key (kbd "<f8> g X") (lambda () (interactive) (insert "Χ") ))
(global-set-key (kbd "<f8> g x") (lambda () (interactive) (insert "χ") ))
(global-set-key (kbd "<f8> g Y") (lambda () (interactive) (insert "Υ") ))
(global-set-key (kbd "<f8> g y") (lambda () (interactive) (insert "υ") ))
(global-set-key (kbd "<f8> g Z") (lambda () (interactive) (insert "Ζ") ))
(global-set-key (kbd "<f8> g z") (lambda () (interactive) (insert "ζ") ))
(global-set-key (kbd "<f8> f A") (lambda () (interactive) (insert "𝔄") ))
(global-set-key (kbd "<f8> f a") (lambda () (interactive) (insert "𝔞") ))
(global-set-key (kbd "<f8> f B") (lambda () (interactive) (insert "𝔅") ))
(global-set-key (kbd "<f8> f b") (lambda () (interactive) (insert "𝔟") ))
(global-set-key (kbd "<f8> f C") (lambda () (interactive) (insert "ℭ") ))
(global-set-key (kbd "<f8> f c") (lambda () (interactive) (insert "𝔠") ))
(global-set-key (kbd "<f8> f D") (lambda () (interactive) (insert "𝔇") ))
(global-set-key (kbd "<f8> f d") (lambda () (interactive) (insert "𝔡") ))
(global-set-key (kbd "<f8> f E") (lambda () (interactive) (insert "𝔈") ))
(global-set-key (kbd "<f8> f e") (lambda () (interactive) (insert "𝔢") ))
(global-set-key (kbd "<f8> f F") (lambda () (interactive) (insert "𝔉") ))
(global-set-key (kbd "<f8> f f") (lambda () (interactive) (insert "𝔣") ))
(global-set-key (kbd "<f8> f G") (lambda () (interactive) (insert "𝔊") ))
(global-set-key (kbd "<f8> f g") (lambda () (interactive) (insert "𝔤") ))
(global-set-key (kbd "<f8> f H") (lambda () (interactive) (insert "ℌ") ))
(global-set-key (kbd "<f8> f h") (lambda () (interactive) (insert "𝔥") ))
(global-set-key (kbd "<f8> f I") (lambda () (interactive) (insert "ℑ") ))
(global-set-key (kbd "<f8> f i") (lambda () (interactive) (insert "𝔦") ))
(global-set-key (kbd "<f8> f J") (lambda () (interactive) (insert "𝔍") ))
(global-set-key (kbd "<f8> f j") (lambda () (interactive) (insert "𝔧") ))
(global-set-key (kbd "<f8> f K") (lambda () (interactive) (insert "𝔎") ))
(global-set-key (kbd "<f8> f k") (lambda () (interactive) (insert "𝔨") ))
(global-set-key (kbd "<f8> f L") (lambda () (interactive) (insert "𝔏") ))
(global-set-key (kbd "<f8> f l") (lambda () (interactive) (insert "𝔩") ))
(global-set-key (kbd "<f8> f M") (lambda () (interactive) (insert "𝔐") ))
(global-set-key (kbd "<f8> f m") (lambda () (interactive) (insert "𝔪") ))
(global-set-key (kbd "<f8> f N") (lambda () (interactive) (insert "𝔑") ))
(global-set-key (kbd "<f8> f n") (lambda () (interactive) (insert "𝔫") ))
(global-set-key (kbd "<f8> f O") (lambda () (interactive) (insert "𝔒") ))
(global-set-key (kbd "<f8> f o") (lambda () (interactive) (insert "𝔬") ))
(global-set-key (kbd "<f8> f P") (lambda () (interactive) (insert "𝔓") ))
(global-set-key (kbd "<f8> f p") (lambda () (interactive) (insert "𝔭") ))
(global-set-key (kbd "<f8> f Q") (lambda () (interactive) (insert "𝔔") ))
(global-set-key (kbd "<f8> f q") (lambda () (interactive) (insert "𝔮") ))
(global-set-key (kbd "<f8> f R") (lambda () (interactive) (insert "ℜ") ))
(global-set-key (kbd "<f8> f r") (lambda () (interactive) (insert "𝔯") ))
(global-set-key (kbd "<f8> f S") (lambda () (interactive) (insert "𝔖") ))
(global-set-key (kbd "<f8> f s") (lambda () (interactive) (insert "𝔰") ))
(global-set-key (kbd "<f8> f T") (lambda () (interactive) (insert "𝔗") ))
(global-set-key (kbd "<f8> f t") (lambda () (interactive) (insert "𝔱") ))
(global-set-key (kbd "<f8> f U") (lambda () (interactive) (insert "𝔘") ))
(global-set-key (kbd "<f8> f u") (lambda () (interactive) (insert "𝔲") ))
(global-set-key (kbd "<f8> f V") (lambda () (interactive) (insert "𝔙") ))
(global-set-key (kbd "<f8> f v") (lambda () (interactive) (insert "𝔳") ))
(global-set-key (kbd "<f8> f W") (lambda () (interactive) (insert "𝔚") ))
(global-set-key (kbd "<f8> f w") (lambda () (interactive) (insert "𝔴") ))
(global-set-key (kbd "<f8> f X") (lambda () (interactive) (insert "𝔛") ))
(global-set-key (kbd "<f8> f x") (lambda () (interactive) (insert "𝔵") ))
(global-set-key (kbd "<f8> f Y") (lambda () (interactive) (insert "𝔜") ))
(global-set-key (kbd "<f8> f y") (lambda () (interactive) (insert "𝔶") ))
(global-set-key (kbd "<f8> f Z") (lambda () (interactive) (insert "ℨ") ))
(global-set-key (kbd "<f8> f z") (lambda () (interactive) (insert "𝔷") ))
(global-set-key (kbd "<f8> h a") (lambda () (interactive) (insert "ℵ") ))
(global-set-key (kbd "<f8> h b") (lambda () (interactive) (insert "ℶ") ))
(global-set-key (kbd "<f8> h g") (lambda () (interactive) (insert "ℷ") ))
(global-set-key (kbd "<f8> h d") (lambda () (interactive) (insert "ℸ") ))
(global-set-key (kbd "<f8> * * *") (lambda () (interactive) (insert "⁂") ))
(global-set-key (kbd "<f8> S S") (lambda () (interactive) (insert "§") ))
(global-set-key (kbd "<f8> < |") (lambda () (interactive) (insert "⊲") ))
(global-set-key (kbd "<f8> | >") (lambda () (interactive) (insert "⊳") ))
(global-set-key (kbd "<f8> _ v") (lambda () (interactive) (insert "∇") ))
(global-set-key (kbd "<f8> _ ^") (lambda () (interactive) (insert "∆") ))
(global-set-key (kbd "<f8> [ ]") (lambda () (interactive) (insert "□") ))
(global-set-key (kbd "<f8> q e d") (lambda () (interactive) (insert "□") ))
(global-set-key (kbd "<f8> 5 [ ]") (lambda () (interactive) (insert "⬠") ))
(global-set-key (kbd "<f8> 6 [ ]") (lambda () (interactive) (insert "⬡") ))
(global-set-key (kbd "<f8> 6 [ | ]") (lambda () (interactive) (insert "⌬") ))
(global-set-key (kbd "<f8> v ^") (lambda () (interactive) (insert "◊") ))
(global-set-key (kbd "<f8> ^ v") (lambda () (interactive) (insert "◊") ))
(global-set-key (kbd "<f8> * SPC") (lambda () (interactive) (insert "⋆") ))
(global-set-key (kbd "<f8> b A") (lambda () (interactive) (insert "𝔸") ))
(global-set-key (kbd "<f8> b a") (lambda () (interactive) (insert "𝕒") ))
(global-set-key (kbd "<f8> b B") (lambda () (interactive) (insert "𝔹") ))
(global-set-key (kbd "<f8> b b") (lambda () (interactive) (insert "𝕓") ))
(global-set-key (kbd "<f8> b C") (lambda () (interactive) (insert "ℂ") ))
(global-set-key (kbd "<f8> b c") (lambda () (interactive) (insert "𝕔") ))
(global-set-key (kbd "<f8> b D") (lambda () (interactive) (insert "𝔻") ))
(global-set-key (kbd "<f8> b d") (lambda () (interactive) (insert "𝕕") ))
(global-set-key (kbd "<f8> b E") (lambda () (interactive) (insert "𝔼") ))
(global-set-key (kbd "<f8> b e") (lambda () (interactive) (insert "𝕖") ))
(global-set-key (kbd "<f8> b F") (lambda () (interactive) (insert "𝔽") ))
(global-set-key (kbd "<f8> b f") (lambda () (interactive) (insert "𝕗") ))
(global-set-key (kbd "<f8> b G") (lambda () (interactive) (insert "𝔾") ))
(global-set-key (kbd "<f8> b g") (lambda () (interactive) (insert "𝕘") ))
(global-set-key (kbd "<f8> b H") (lambda () (interactive) (insert "ℍ") ))
(global-set-key (kbd "<f8> b h") (lambda () (interactive) (insert "𝕙") ))
(global-set-key (kbd "<f8> b I") (lambda () (interactive) (insert "𝕀") ))
(global-set-key (kbd "<f8> b i") (lambda () (interactive) (insert "𝕚") ))
(global-set-key (kbd "<f8> b J") (lambda () (interactive) (insert "𝕁") ))
(global-set-key (kbd "<f8> b j") (lambda () (interactive) (insert "𝕛") ))
(global-set-key (kbd "<f8> b K") (lambda () (interactive) (insert "𝕂") ))
(global-set-key (kbd "<f8> b k") (lambda () (interactive) (insert "𝕜") ))
(global-set-key (kbd "<f8> b L") (lambda () (interactive) (insert "𝕃") ))
(global-set-key (kbd "<f8> b l") (lambda () (interactive) (insert "𝕝") ))
(global-set-key (kbd "<f8> b M") (lambda () (interactive) (insert "𝕄") ))
(global-set-key (kbd "<f8> b m") (lambda () (interactive) (insert "𝕞") ))
(global-set-key (kbd "<f8> b N") (lambda () (interactive) (insert "ℕ") ))
(global-set-key (kbd "<f8> b n") (lambda () (interactive) (insert "𝕟") ))
(global-set-key (kbd "<f8> b O") (lambda () (interactive) (insert "𝕆") ))
(global-set-key (kbd "<f8> b o") (lambda () (interactive) (insert "𝕠") ))
(global-set-key (kbd "<f8> b P") (lambda () (interactive) (insert "ℙ") ))
(global-set-key (kbd "<f8> b p") (lambda () (interactive) (insert "𝕡") ))
(global-set-key (kbd "<f8> b Q") (lambda () (interactive) (insert "ℚ") ))
(global-set-key (kbd "<f8> b q") (lambda () (interactive) (insert "𝕢") ))
(global-set-key (kbd "<f8> b R") (lambda () (interactive) (insert "ℝ") ))
(global-set-key (kbd "<f8> b r") (lambda () (interactive) (insert "𝕣") ))
(global-set-key (kbd "<f8> b S") (lambda () (interactive) (insert "𝕊") ))
(global-set-key (kbd "<f8> b s") (lambda () (interactive) (insert "𝕤") ))
(global-set-key (kbd "<f8> b T") (lambda () (interactive) (insert "𝕋") ))
(global-set-key (kbd "<f8> b t") (lambda () (interactive) (insert "𝕥") ))
(global-set-key (kbd "<f8> b U") (lambda () (interactive) (insert "𝕌") ))
(global-set-key (kbd "<f8> b u") (lambda () (interactive) (insert "𝕦") ))
(global-set-key (kbd "<f8> b V") (lambda () (interactive) (insert "𝕍") ))
(global-set-key (kbd "<f8> b v") (lambda () (interactive) (insert "𝕧") ))
(global-set-key (kbd "<f8> b W") (lambda () (interactive) (insert "𝕎") ))
(global-set-key (kbd "<f8> b w") (lambda () (interactive) (insert "𝕨") ))
(global-set-key (kbd "<f8> b X") (lambda () (interactive) (insert "𝕏") ))
(global-set-key (kbd "<f8> b x") (lambda () (interactive) (insert "𝕩") ))
(global-set-key (kbd "<f8> b Y") (lambda () (interactive) (insert "𝕐") ))
(global-set-key (kbd "<f8> b y") (lambda () (interactive) (insert "𝕪") ))
(global-set-key (kbd "<f8> b Z") (lambda () (interactive) (insert "ℤ") ))
(global-set-key (kbd "<f8> b z") (lambda () (interactive) (insert "𝕫") ))
(global-set-key (kbd "<f8> b 0") (lambda () (interactive) (insert "𝟘") ))
(global-set-key (kbd "<f8> b 1") (lambda () (interactive) (insert "𝟙") ))
(global-set-key (kbd "<f8> b 2") (lambda () (interactive) (insert "𝟚") ))
(global-set-key (kbd "<f8> b 3") (lambda () (interactive) (insert "𝟛") ))
(global-set-key (kbd "<f8> b 4") (lambda () (interactive) (insert "𝟜") ))
(global-set-key (kbd "<f8> b 5") (lambda () (interactive) (insert "𝟝") ))
(global-set-key (kbd "<f8> b 6") (lambda () (interactive) (insert "𝟞") ))
(global-set-key (kbd "<f8> b 7") (lambda () (interactive) (insert "𝟟") ))
(global-set-key (kbd "<f8> b 8") (lambda () (interactive) (insert "𝟠") ))
(global-set-key (kbd "<f8> b 9") (lambda () (interactive) (insert "𝟡") ))
(global-set-key (kbd "<f8> l A E") (lambda () (interactive) (insert "Æ") ))
(global-set-key (kbd "<f8> l A e") (lambda () (interactive) (insert "Æ") ))
(global-set-key (kbd "<f8> l a e") (lambda () (interactive) (insert "æ") ))
(global-set-key (kbd "<f8> a e") (lambda () (interactive) (insert "æ") ))
(global-set-key (kbd "<f8> ' A") (lambda () (interactive) (insert "Á") ))
(global-set-key (kbd "<f8> ` A") (lambda () (interactive) (insert "À") ))
(global-set-key (kbd "<f8> \" A") (lambda () (interactive) (insert "Ä") ))
(global-set-key (kbd "<f8> ^ A") (lambda () (interactive) (insert "Â") ))
(global-set-key (kbd "<f8> ~ A") (lambda () (interactive) (insert "Ã") ))
(global-set-key (kbd "<f8> o A") (lambda () (interactive) (insert "Å") ))
(global-set-key (kbd "<f8> ' a") (lambda () (interactive) (insert "á") ))
(global-set-key (kbd "<f8> ` a") (lambda () (interactive) (insert "à") ))
(global-set-key (kbd "<f8> \" a") (lambda () (interactive) (insert "ä") ))
(global-set-key (kbd "<f8> ^ a") (lambda () (interactive) (insert "â") ))
(global-set-key (kbd "<f8> ~ a") (lambda () (interactive) (insert "ã") ))
(global-set-key (kbd "<f8> o a") (lambda () (interactive) (insert "å") ))
(global-set-key (kbd "<f8> C 5") (lambda () (interactive) (insert "Ç") ))
(global-set-key (kbd "<f8> c 5") (lambda () (interactive) (insert "ç") ))
(global-set-key (kbd "<f8> D -") (lambda () (interactive) (insert "Ð") ))
(global-set-key (kbd "<f8> - D") (lambda () (interactive) (insert "Ð") ))
(global-set-key (kbd "<f8> d -") (lambda () (interactive) (insert "ð") ))
(global-set-key (kbd "<f8> - d") (lambda () (interactive) (insert "ð") ))
(global-set-key (kbd "<f8> ' E") (lambda () (interactive) (insert "É") ))
(global-set-key (kbd "<f8> ` E") (lambda () (interactive) (insert "È") ))
(global-set-key (kbd "<f8> \" E") (lambda () (interactive) (insert "Ë") ))
(global-set-key (kbd "<f8> ^ E") (lambda () (interactive) (insert "Ê") ))
(global-set-key (kbd "<f8> ~ E") (lambda () (interactive) (insert "Ẽ") ))
(global-set-key (kbd "<f8> ' e") (lambda () (interactive) (insert "é") ))
(global-set-key (kbd "<f8> ` e") (lambda () (interactive) (insert "è") ))
(global-set-key (kbd "<f8> \" e") (lambda () (interactive) (insert "ë") ))
(global-set-key (kbd "<f8> ^ e") (lambda () (interactive) (insert "ê") ))
(global-set-key (kbd "<f8> ~ e") (lambda () (interactive) (insert "ẽ") ))
(global-set-key (kbd "<f8> ' I") (lambda () (interactive) (insert "Í") ))
(global-set-key (kbd "<f8> ` I") (lambda () (interactive) (insert "Ì") ))
(global-set-key (kbd "<f8> \" I") (lambda () (interactive) (insert "Ï") ))
(global-set-key (kbd "<f8> ^ I") (lambda () (interactive) (insert "Î") ))
(global-set-key (kbd "<f8> ~ I") (lambda () (interactive) (insert "Ĩ") ))
(global-set-key (kbd "<f8> ' i") (lambda () (interactive) (insert "í") ))
(global-set-key (kbd "<f8> ` i") (lambda () (interactive) (insert "ì") ))
(global-set-key (kbd "<f8> \" i") (lambda () (interactive) (insert "ï") ))
(global-set-key (kbd "<f8> ^ i") (lambda () (interactive) (insert "î") ))
(global-set-key (kbd "<f8> ~ i") (lambda () (interactive) (insert "ĩ") ))
(global-set-key (kbd "<f8> ~ N") (lambda () (interactive) (insert "Ñ") ))
(global-set-key (kbd "<f8> ~ n") (lambda () (interactive) (insert "ñ") ))
(global-set-key (kbd "<f8> ' O") (lambda () (interactive) (insert "Ó") ))
(global-set-key (kbd "<f8> ` O") (lambda () (interactive) (insert "Ò") ))
(global-set-key (kbd "<f8> \" O") (lambda () (interactive) (insert "Ö") ))
(global-set-key (kbd "<f8> ^ O") (lambda () (interactive) (insert "Ô") ))
(global-set-key (kbd "<f8> ~ O") (lambda () (interactive) (insert "Õ") ))
(global-set-key (kbd "<f8> ' o") (lambda () (interactive) (insert "ó") ))
(global-set-key (kbd "<f8> ` o") (lambda () (interactive) (insert "ò") ))
(global-set-key (kbd "<f8> \" o") (lambda () (interactive) (insert "ö") ))
(global-set-key (kbd "<f8> ^ o") (lambda () (interactive) (insert "ô") ))
(global-set-key (kbd "<f8> ~ o") (lambda () (interactive) (insert "õ") ))
(global-set-key (kbd "<f8> / O") (lambda () (interactive) (insert "Ø") ))
(global-set-key (kbd "<f8> / o") (lambda () (interactive) (insert "ø") ))
(global-set-key (kbd "<f8> l O E") (lambda () (interactive) (insert "Œ") ))
(global-set-key (kbd "<f8> l O e") (lambda () (interactive) (insert "Œ") ))
(global-set-key (kbd "<f8> O E") (lambda () (interactive) (insert "Œ") ))
(global-set-key (kbd "<f8> O e") (lambda () (interactive) (insert "Œ") ))
(global-set-key (kbd "<f8> l o e") (lambda () (interactive) (insert "œ") ))
(global-set-key (kbd "<f8> o e") (lambda () (interactive) (insert "œ") ))
(global-set-key (kbd "<f8> s s") (lambda () (interactive) (insert "ß") ))
(global-set-key (kbd "<f8> ' U") (lambda () (interactive) (insert "Ú") ))
(global-set-key (kbd "<f8> ` U") (lambda () (interactive) (insert "Ù") ))
(global-set-key (kbd "<f8> \" U") (lambda () (interactive) (insert "Ü") ))
(global-set-key (kbd "<f8> ^ U") (lambda () (interactive) (insert "Û") ))
(global-set-key (kbd "<f8> ~ U") (lambda () (interactive) (insert "Ũ") ))
(global-set-key (kbd "<f8> ' u") (lambda () (interactive) (insert "ú") ))
(global-set-key (kbd "<f8> ` u") (lambda () (interactive) (insert "ù") ))
(global-set-key (kbd "<f8> \" u") (lambda () (interactive) (insert "ü") ))
(global-set-key (kbd "<f8> ^ u") (lambda () (interactive) (insert "û") ))
(global-set-key (kbd "<f8> ~ u") (lambda () (interactive) (insert "ũ") ))
(global-set-key (kbd "<f8> ' Y") (lambda () (interactive) (insert "Ý") ))
(global-set-key (kbd "<f8> ` Y") (lambda () (interactive) (insert "Ỳ") ))
(global-set-key (kbd "<f8> \" Y") (lambda () (interactive) (insert "Ÿ") ))
(global-set-key (kbd "<f8> ^ Y") (lambda () (interactive) (insert "Ŷ") ))
(global-set-key (kbd "<f8> ~ Y") (lambda () (interactive) (insert "Ỹ") ))
(global-set-key (kbd "<f8> ' y") (lambda () (interactive) (insert "ý") ))
(global-set-key (kbd "<f8> ` y") (lambda () (interactive) (insert "ỳ") ))
(global-set-key (kbd "<f8> \" y") (lambda () (interactive) (insert "ÿ") ))
(global-set-key (kbd "<f8> ^ y") (lambda () (interactive) (insert "ŷ") ))
(global-set-key (kbd "<f8> ~ y") (lambda () (interactive) (insert "ỹ") ))
(global-set-key (kbd "<f8> l E t h") (lambda () (interactive) (insert "Ð") ))
(global-set-key (kbd "<f8> l E T H") (lambda () (interactive) (insert "Ð") ))
(global-set-key (kbd "<f8> l e t h") (lambda () (interactive) (insert "ð") ))
(global-set-key (kbd "<f8> l T h o r n") (lambda () (interactive) (insert "Þ") ))
(global-set-key (kbd "<f8> l T H O R N") (lambda () (interactive) (insert "Þ") ))
(global-set-key (kbd "<f8> l t h o r n") (lambda () (interactive) (insert "þ") ))
(global-set-key (kbd "<f8> \\ f o r a l l") (lambda () (interactive) (insert "∀") ))
(global-set-key (kbd "<f8> c currency") (lambda () (interactive) (insert "¤") ))
(global-set-key (kbd "<f8> c x o") (lambda () (interactive) (insert "¤") ))
(global-set-key (kbd "<f8> c u s d") (lambda () (interactive) (insert "$") ))
(global-set-key (kbd "<f8> c c e n t") (lambda () (interactive) (insert "¢") ))
(global-set-key (kbd "<f8> c g h s") (lambda () (interactive) (insert "¢") ))
(global-set-key (kbd "<f8> c g b p") (lambda () (interactive) (insert "£") ))
(global-set-key (kbd "<f8> c p o u n d") (lambda () (interactive) (insert "£") ))
(global-set-key (kbd "<f8> c e u r") (lambda () (interactive) (insert "€") ))
(global-set-key (kbd "<f8> c c r c") (lambda () (interactive) (insert "₡") ))
(global-set-key (kbd "<f8> c c n y") (lambda () (interactive) (insert "¥") ))
(global-set-key (kbd "<f8> c y u a n") (lambda () (interactive) (insert "¥") ))
(global-set-key (kbd "<f8> c j p y") (lambda () (interactive) (insert "¥") ))
(global-set-key (kbd "<f8> c y e n") (lambda () (interactive) (insert "¥") ))
(global-set-key (kbd "<f8> c a w g") (lambda () (interactive) (insert "ƒ") ))
(global-set-key (kbd "<f8> c g u i l d e r") (lambda () (interactive) (insert "ƒ") ))
(global-set-key (kbd "<f8> c f r a n c") (lambda () (interactive) (insert "₣") ))
(global-set-key (kbd "<f8> c a z n") (lambda () (interactive) (insert "₼") ))
(global-set-key (kbd "<f8> c k h r") (lambda () (interactive) (insert "៛") ))
(global-set-key (kbd "<f8> c i l s") (lambda () (interactive) (insert "₪") ))
(global-set-key (kbd "<f8> c s h e k e l") (lambda () (interactive) (insert "₪") ))
(global-set-key (kbd "<f8> c c u p") (lambda () (interactive) (insert "₱") ))
(global-set-key (kbd "<f8> c k r w") (lambda () (interactive) (insert "₩") ))
(global-set-key (kbd "<f8> c w o n") (lambda () (interactive) (insert "₩") ))
(global-set-key (kbd "<f8> c n g n") (lambda () (interactive) (insert "₦") ))
(global-set-key (kbd "<f8> c n a i r a") (lambda () (interactive) (insert "₦") ))
(global-set-key (kbd "<f8> c m n t") (lambda () (interactive) (insert "₮") ))
(global-set-key (kbd "<f8> c t u g h r i k") (lambda () (interactive) (insert "₮") ))
(global-set-key (kbd "<f8> c r i y a l") (lambda () (interactive) (insert "﷼") ))
(global-set-key (kbd "<f8> c r u b") (lambda () (interactive) (insert "₽") ))
(global-set-key (kbd "<f8> c t h b") (lambda () (interactive) (insert "฿") ))
(global-set-key (kbd "<f8> c b a h t") (lambda () (interactive) (insert "฿") ))
(global-set-key (kbd "<f8> ! !") (lambda () (interactive) (insert "¡") ))
(global-set-key (kbd "<f8> ?") (lambda () (interactive) (insert "¿") ))
(global-set-key (kbd "<f8> < <") (lambda () (interactive) (insert "«") ))
(global-set-key (kbd "<f8> > >") (lambda () (interactive) (insert "»") ))
(global-set-key (kbd "<f8> d |") (lambda () (interactive) (insert "│") ))
(global-set-key (kbd "<f8> d -") (lambda () (interactive) (insert "─") ))
(global-set-key (kbd "<f8> d l") (lambda () (interactive) (insert "└") ))
(global-set-key (kbd "<f8> d L") (lambda () (interactive) (insert "└") ))
(global-set-key (kbd "<f8> d 7") (lambda () (interactive) (insert "┐") ))
(global-set-key (kbd "<f8> d r") (lambda () (interactive) (insert "┌") ))
(global-set-key (kbd "<f8> d g") (lambda () (interactive) (insert "┌") ))
(global-set-key (kbd "<f8> d ,") (lambda () (interactive) (insert "┘") ))
(global-set-key (kbd "<f8> d /") (lambda () (interactive) (insert "┘") ))
